server:
  port: 8070

tio:
  websocket:
    server:
      port: 9873
      heartbeat-timeout: 60000
    cluster:
      enabled: true
      group: true
      redis:
        ip: 127.0.0.1
        port: 6379



